Front end inicial
dnlcarvajalc/sirena_project pull request #5
Opened 2024-01-25 19:21 UTC by ManuelaCorreaLopez

2024-01-25 20:08 UTC, lmfranco21 requested changes

2024-01-25 20:08 UTC, lmfranco21 commented on frontend/img/1.png
Elimina todas las imágenes que ya no uses

2024-01-25 20:08 UTC, lmfranco21 commented on frontend/index.html
> +            <div id="imagenContainer" class="imagen-container">
Para todos los Ids class name acostúmbrate a nombrarlos en inglés y eligiendo una sola manera de nombrar o lo haces en camelCase o separado con -

2024-01-25 20:08 UTC, lmfranco21 commented on frontend/src/main.js
> +    const imagen = document.getElementById('imagenAleatoria')
Ajústale el nombre a las variables

2024-01-25 20:08 UTC, lmfranco21 commented on frontend/src/main.js
> +function mostrarInformacionImagen() {
Nombre del método en inglés

2024-01-25 20:08 UTC, lmfranco21 commented on frontend/styles/app.css
> +    /* margin-bottom: 0.5px; */
Elimina texto comentado

2024-01-25 21:29 UTC, ManuelaCorreaLopez commented on frontend/index.html
> +            <div id="imagenContainer" class="imagen-container">
Resuelto

2024-01-25 21:29 UTC, ManuelaCorreaLopez commented on frontend/src/main.js
> +    const imagen = document.getElementById('imagenAleatoria')
Resuelto

2024-01-25 21:29 UTC, ManuelaCorreaLopez commented on frontend/src/main.js
> +function mostrarInformacionImagen() {
Resuelto

2024-01-25 21:29 UTC, ManuelaCorreaLopez commented on frontend/styles/app.css
> +    /* margin-bottom: 0.5px; */
Resuelto

2024-01-26 00:35 UTC, linaf21 approved these changes

2024-01-26 01:47 UTC, merged